version: "3.4"
services:
 vite_docker:
   image: node:alpine
   container_name: trakopenapiinspector_docker
   entrypoint: /bin/sh
   ports:
     - 5150:5150
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   tty: true
